version: 2

sources:
  - name: raw_tables
    description: "Raw data loaded from raw"
    database: DAGSTER_TEST
    schema: RAW
    tables:
      - name: raw_rankings
        description: RAW_RANKINGS Table"
        freshness:
          warn_after: {count: 24, period: hour}
        loaded_at_field: generated_at
        meta:
          dagster:
            asset_key: ["rankings_table"]
      - name: raw_matches
        description: SUPER MATCHES
        meta:
          dagster:
            asset_key: ["matches_table"]
