dbt_dagster:
  outputs:
    target:
      account: "{{ env_var('SF_ACCOUNT') }}"
      database: DAGSTER_TEST
      password: "{{ env_var('SF_PASSWORD') }}"
      role: ACCOUNTADMIN
      schema: sandbox_vduarte
      threads: 4
      type: snowflake
      user: "{{ env_var('SF_USER') }}"
      warehouse: COMPUTE_WH
    dev:
      account: "{{ env_var('SF_ACCOUNT') }}"
      database: DAGSTER_TEST
      password: "{{ env_var('SF_PASSWORD') }}"
      role: ACCOUNTADMIN
      schema: RAW
      threads: 4
      type: snowflake
      user: "{{ env_var('SF_USER') }}"
      warehouse: COMPUTE_WH
  target: target
